repos:

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.10
    exclude: __version__.py
    # args: [--safe, --quiet, --skip-string-normalization]

# Syntax check and flake8 checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-encoding-pragma
  - id: double-quote-string-fixer
  # - id: flake8
  #   args: ['--max-line-length=100', '--select=E401,E711,E712,E713,E714,E721,E722,E901,F401,F402,F403,F405,F631,F632,F633,F811,F812,F821,F822,F841,F901,W191,W291,W292,W293,W602,W603,W604,W605,W606']

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files"]
